### ISSUE TITLE
Continually restarting when I try to run the docker

### ISSUE THREAD

**Issue by adam110th** [Gronis/docker-seafile-client#4]
Hi there,

I have just installed this today and having troubles getting the docker to load. Whenever I start the docker it sits in a reboot cycle. It seems to be falling over on the following command: 

seaf-cli: error: unrecognized arguments: Library

For reference i'm installing it on a synology NAS, and this is an example log output that i receive:

date | stream | content
-- | -- | --
2019-08-07 06:40:18 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:40:18 | stdout | ...
2019-08-07 06:40:18 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:40:18 | stdout |  
2019-08-07 06:40:18 | stdout | usage: seaf-cli [-h]
2019-08-07 06:40:18 | stdout | Syncing My Library
2019-08-07 06:40:16 | stdout | Started: seafile daemon ...
2019-08-07 06:40:16 | stdout | Starting seafile daemon ...
2019-08-07 06:40:15 | stdout | Started: ccnet daemon ...
2019-08-07 06:40:15 | stdout | Starting ccnet daemon ...
2019-08-07 06:40:12 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:40:12 | stdout | ...
2019-08-07 06:40:12 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:40:12 | stdout |  
2019-08-07 06:40:12 | stdout | usage: seaf-cli [-h]
2019-08-07 06:40:12 | stdout | Syncing My Library
2019-08-07 06:40:10 | stdout | Started: seafile daemon ...
2019-08-07 06:40:10 | stdout | Starting seafile daemon ...
2019-08-07 06:40:09 | stdout | Started: ccnet daemon ...
2019-08-07 06:40:09 | stdout | Starting ccnet daemon ...
2019-08-07 06:40:06 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:40:06 | stdout | ...
2019-08-07 06:40:06 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:40:06 | stdout |  
2019-08-07 06:40:06 | stdout | usage: seaf-cli [-h]
2019-08-07 06:40:06 | stdout | Syncing My Library
2019-08-07 06:40:05 | stdout | Started: seafile daemon ...
2019-08-07 06:40:05 | stdout | Starting seafile daemon ...
2019-08-07 06:40:04 | stdout | Started: ccnet daemon ...
2019-08-07 06:40:04 | stdout | Starting ccnet daemon ...
2019-08-07 06:40:01 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:40:01 | stdout | ...
2019-08-07 06:40:01 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:40:01 | stdout |  
2019-08-07 06:40:01 | stdout | usage: seaf-cli [-h]
2019-08-07 06:40:00 | stdout | Syncing My Library
2019-08-07 06:39:59 | stdout | Started: seafile daemon ...
2019-08-07 06:39:59 | stdout | Starting seafile daemon ...
2019-08-07 06:39:58 | stdout | Started: ccnet daemon ...
2019-08-07 06:39:58 | stdout | Starting ccnet daemon ...
2019-08-07 06:39:55 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:39:55 | stdout | ...
2019-08-07 06:39:55 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:39:55 | stdout |  
2019-08-07 06:39:55 | stdout | usage: seaf-cli [-h]
2019-08-07 06:39:55 | stdout | Syncing My Library
2019-08-07 06:39:54 | stdout | Started: seafile daemon ...
2019-08-07 06:39:54 | stdout | Starting seafile daemon ...
2019-08-07 06:39:53 | stdout | Started: ccnet daemon ...
2019-08-07 06:39:53 | stdout | Starting ccnet daemon ...
2019-08-07 06:39:50 | stdout | seaf-cli: error: unrecognized arguments: Library
2019-08-07 06:39:50 | stdout | ...
2019-08-07 06:39:50 | stdout | {init,start,stop,list,list-remote,status,download,download-by-name,sync,desync,create,config}
2019-08-07 06:39:50 | stdout |  
2019-08-07 06:39:50 | stdout | usage: seaf-cli [-h]
2019-08-07 06:39:49 | stdout | Syncing My Library
2019-08-07 06:39:47 | stdout | Started: seafile daemon ...
2019-08-07 06:39:46 | stdout | Starting seafile daemon ...
2019-08-07 06:39:45 | stdout | Started: ccnet daemon ...
2019-08-07 06:39:45 | stdout | Starting ccnet daemon ...

Thanks,
Adam.

**Comment by Gronis** [comment]
Hi, could you post the environment variables and other parameters used when starting up the container? You need to setup some environment variables to tell the seafile-client container what libraries to get and from which server etc.

**Comment by jocarren** [comment]
Your build in dockerhub gives this same problem. I suspect is out of date.

**Comment by Gronis** [comment]
I'm pretty sure that one is not out of date. Have you built the image from master and compared the results? If the image on dockerhub is out of date, and a fresh build does not have this issue, I can update the image on dockerhub. However, I don't recall ever implementing a fix for this issue, so I suspect it might still be in there. 

Edit: I just pulled the image from dockerhub and tested it on my personal setup. I think this problem is related to the library name.

**Comment by Gronis** [comment]
I've managed to recreate the problem. The problem should have been fixed. Please test with the newest image on dockerhub and verify that it works.

**Comment by jocarren** [comment]
This is the output when syncronizing library "Mi Biblioteca"

```
New device id created

Starting seafile daemon ...

Started: seafile daemon ...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 1/100000 exited 1, retrying in 1 seconds...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 2/100000 exited 1, retrying in 2 seconds...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 3/100000 exited 1, retrying in 4 seconds...

# Name Status Progress

# Name Status

exiting

Using new data directory: /library

Syncing Mi Biblioteca

Starting to download ...

2020-02-10 20:20:16

# Name Status Progress

Mi Biblioteca downloading 0/1, 0.0KB/s

# Name Status

2020-02-10 20:21:18

# Name Status Progress

# Name Status

Mi Biblioteca synchronized

2020-02-10 20:22:20

# Name Status Progress

# Name Status

Mi Biblioteca synchronized
```

Works fine, but when trying "Diseño y Ejecución de Servicios", it returns:
```

New device id created

Starting seafile daemon ...

Started: seafile daemon ...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 1/100000 exited 1, retrying in 1 seconds...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 2/100000 exited 1, retrying in 2 seconds...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 3/100000 exited 1, retrying in 4 seconds...

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 660, in seaf_status

tasks = seafile_rpc.get_clone_tasks()

File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc

ret_str = self.call_remote_func_sync(fcall_str)

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync

self.transport.connect()

File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect

self.pipe_fd.connect(self.socket_path)

File "/usr/lib/python2.7/socket.py", line 228, in meth

return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

Retry 4/100000 exited 1, retrying in 8 seconds...

# Name Status Progress

# Name Status

exiting

Using new data directory: /library

Syncing Dise\u00f1o y Ejecuci\u00f3n de Servicios

Starting to download ...

2020-02-10 20:26:59

# Name Status Progress

Traceback (most recent call last):

File "/usr/bin/seaf-cli", line 869, in <module>

main()

File "/usr/bin/seaf-cli", line 865, in main

args.func(args)

File "/usr/bin/seaf-cli", line 667, in seaf_status

tx_task.rate/1024.0)

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 4: ordinal not in range(128)
```

Looks like there is a problem with the "ñ" character. 

I built the image in my setup from 5b2af75ae994fbfdbce31d97d9d71bc14bc3d299, worked fine on both libraries.

**Comment by Gronis** [comment]
Hi @jocarren.
Are you saying that if you build with commit `5b2af75`, it works for both these cases? That is really strange if that is the case, because that was the version used when this issue was first published.

**Comment by Gronis** [comment]
Closing this issue due to inactivity.
