### ISSUE TITLE
socket.error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jonatino** [Gronis/docker-seafile-client#8]
```
Starting seafile daemon ...
Started: seafile daemon ...
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 660, in seaf_status
tasks = seafile_rpc.get_clone_tasks()
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Retry 1/5 exited 1, retrying in 1 seconds...
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 660, in seaf_status
tasks = seafile_rpc.get_clone_tasks()
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Retry 2/5 exited 1, retrying in 2 seconds...
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 660, in seaf_status
tasks = seafile_rpc.get_clone_tasks()
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Retry 3/5 exited 1, retrying in 4 seconds...
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 660, in seaf_status
tasks = seafile_rpc.get_clone_tasks()
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Retry 4/5 exited 1, retrying in 8 seconds...
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 660, in seaf_status
tasks = seafile_rpc.get_clone_tasks()
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Retry 5/5 exited 1, no more retries left.
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 360, in seaf_list
repos = seafile_rpc.get_repo_list(-1, -1)
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory

Syncing Sync
Traceback (most recent call last):
File "/usr/bin/seaf-cli", line 869, in <module>
Starting to download ...
main()
File "/usr/bin/seaf-cli", line 865, in main
args.func(args)
File "/usr/bin/seaf-cli", line 600, in seaf_sync
email, random_key, enc_version, more_info)
File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
ret_str = self.call_remote_func_sync(fcall_str)
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
self.transport.connect()
File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
self.pipe_fd.connect(self.socket_path)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

Running on unraid.

Screenshot of setup:
https://dl.dropboxusercontent.com/s/ys7odqh9h1aytmv/chrome_v8YLbgQhY4.png

**Comment by Gronis** [comment]
Hi, thanks for reporting. Is your system x86 based? I believe that the image only supports x86 hardware for now.

**Comment by Gronis** [comment]
Closing this issue due to inactivity.
